### ISSUE TITLE
Fail to authenticate

### ISSUE THREAD

**Issue by GolfMan2000** [microsoftgraph/xamarin-csharp-photosender-sample#4]
in SignInPage

in SiignIn
                var result = await App.PCA.AcquireTokenAsync(App.AppScopes, App.AuthUiParent);

throws an exception where AuthUiParent is null

**Comment by jasonjoh** [comment]
Closing this as we are archiving this repository and no longer maintaining it. Please see [Build Xamarin apps with Microsoft Graph](https://github.com/microsoftgraph/msgraph-training-xamarin) for a current sample.
